version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: cryptobot_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: cryptobot
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: cryptobot_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - cryptobot_network
    ports:
      - "27017:27017"

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: cryptobot_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - cryptobot_network
    ports:
      - "6379:6379"

  # Freqtrade Bot
  freqtrade:
    build:
      context: ./freqtrade  # Assumes your Freqtrade code is in a 'freqtrade' folder
      dockerfile: Dockerfile
    container_name: cryptobot_freqtrade
    restart: unless-stopped
    depends_on:
      - mongodb
    volumes:
      - freqtrade_data:/freqtrade/user_data
      - ./freqtrade/config.json:/freqtrade/config.json:ro # Mount config read-only
    networks:
      - cryptobot_network
    # Freqtrade does not need to expose ports unless you use its UI, which we can add later.

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cryptobot_backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://cryptobot:${MONGO_PASSWORD}@mongodb:27017/cryptobot_db?authSource=admin
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - LUNO_API_KEY=${LUNO_API_KEY}
      - LUNO_API_SECRET=${LUNO_API_SECRET}
      - API_TOKEN=${API_TOKEN}
      # ... add all your other backend environment variables here ...
    depends_on:
      - mongodb
      - redis
      - freqtrade # Backend now depends on Freqtrade
    networks:
      - cryptobot_network
    ports:
      - "8004:8004"

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cryptobot_frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - cryptobot_network
    ports:
      - "3003:3000"

networks:
  cryptobot_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  freqtrade_data:
