services:
  mongodb:
    image: mongo:7
    container_name: crypto-coach-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - crypto-coach-network
    ports:
      - "127.0.0.1:27018:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto-coach-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
    env_file:
      - ../.env
    networks:
      - crypto-coach-network
    ports:
      - "8002:8001"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: crypto-coach-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=https://crypto.zikhethele.properties/api
    networks:
      - crypto-coach-network
    ports:
      - "3001:3000"

  freqtrade:
    build:
      context: .
      dockerfile: freqtrade/Dockerfile
    container_name: crypto-coach-freqtrade
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - crypto-coach-network
    ports:
      - "127.0.0.1:8083:8082"

networks:
  crypto-coach-network:
    driver: bridge

volumes:
  mongodb_data:
  backend_logs:
  freqtrade_logs: