name: CI/CD Pipeline - AI Crypto Trading Coach

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: app/frontend/package-lock.json
    
    - name: Install Frontend Dependencies
      run: |
        cd app/frontend
        npm ci
    
    - name: Run Frontend Build Test
      run: |
        cd app/frontend
        npm run build
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Backend Dependencies
      run: |
        cd app/backend
        pip install -r requirements.txt
    
    - name: Test Backend Import
      run: |
        cd app/backend
        python -c "import server; print('Backend imports successfully')"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push Backend Image
      run: |
        docker build -f docker/Dockerfile.backend.prod -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/backend:latest app/backend
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/backend:latest
    
    - name: Build and Push Frontend Image  
      run: |
        docker build -f docker/Dockerfile.frontend.prod -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/frontend:latest app/frontend
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/frontend:latest
    
    - name: Build and Push Freqtrade Image
      run: |
        docker build -f docker/Dockerfile.freqtrade.prod -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/freqtrade:latest app/freqtrade
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/freqtrade:latest
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /opt/crypto-coach
          
          # Pull latest code
          git pull origin main
          
          # Login to container registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Pull latest images
          docker-compose -f docker/docker-compose.prod.yml pull
          
          # Deploy
          ./scripts/deploy.sh
          
          # Health check
          sleep 30
          ./scripts/health-check.sh || exit 1