version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: crypto-coach-mongo-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - crypto-coach-network
    ports:
      - "127.0.0.1:27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build:
      context: ./vps_deployment_package/app
      dockerfile: ../docker/Dockerfile.backend.prod
    image: henrijc/trading-bot-backend:latest
    container_name: crypto-coach-backend-prod
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - backend_logs:/app/logs
    networks:
      - crypto-coach-network
    ports:
      - "127.0.0.1:8001:8001"
    env_file:
      - /opt/crypto-coach/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./vps_deployment_package/app
      dockerfile: ../docker/Dockerfile.frontend.prod
    image: henrijc/trading-bot-frontend:latest
    container_name: crypto-coach-frontend-prod
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=https://crypto-coach.zikhethele.properties/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - crypto-coach-network
    ports:
      - "127.0.0.1:3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  crypto-coach-network:
    name: crypto-coach-network

volumes:
  mongodb_data:
  backend_logs: