name: Build and Push Docker Images

on:
  push:
    branches: [ for-deployment ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: henrijc/trading-bot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    outputs:
      backend-digest: ${{ steps.backend.outputs.digest }}
      frontend-digest: ${{ steps.frontend.outputs.digest }}
      freqtrade-digest: ${{ steps.freqtrade.outputs.digest }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push backend image
      id: backend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: vps_deployment_package/docker/Dockerfile.backend.prod
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push frontend image
      id: frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: vps_deployment_package/docker/Dockerfile.frontend.prod
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push freqtrade image
      id: freqtrade
      uses: docker/build-push-action@v5
      with:
        context: .
        file: vps_deployment_package/docker/Dockerfile.freqtrade.prod
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-freqtrade:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max