name: Test Password Authentication

on:
  workflow_dispatch:

jobs:
  test-password-auth:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH with Password Authentication
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 156.155.253.224
        username: cryptoadmin
        password: ${{ secrets.VPS_PASSWORD }}
        timeout: 60s
        script: |
          echo "🔑 PASSWORD AUTHENTICATION SUCCESSFUL!"
          echo "=== VPS CONNECTION TEST ==="
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          echo "Date: $(date)"
          echo ""
          
          # Check if project directory exists
          if [ -d "/opt/crypto-coach" ]; then
            echo "✅ /opt/crypto-coach directory found!"
            cd /opt/crypto-coach
            echo "Project directory contents:"
            ls -la | head -5
            echo ""
            
            # Check Docker
            if docker --version > /dev/null 2>&1; then
              echo "✅ Docker is available: $(docker --version)"
            else
              echo "❌ Docker not found"
            fi
            
            # Check Docker Compose
            if docker compose version > /dev/null 2>&1; then
              echo "✅ Docker Compose is available: $(docker compose version)"
            else
              echo "❌ Docker Compose not found"
            fi
            
          else
            echo "❌ /opt/crypto-coach directory NOT found!"
          fi
          
          echo ""
          echo "🎉 PASSWORD AUTH TEST COMPLETED!"