name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 156.155.253.224
        username: cryptoadmin
        key: ${{ secrets.VPS_SSH_C_BOT_KEY }}
        timeout: 30s
        script: |
          echo "✅ SSH Connection Successful!"
          echo "Current directory: $(pwd)"
          echo "User: $(whoami)"
          echo "Date: $(date)"
          echo "Free space: $(df -h / | tail -1)"
          
          # Test if crypto-coach directory exists
          if [ -d "/opt/crypto-coach" ]; then
            echo "✅ /opt/crypto-coach directory exists"
            echo "Contents: $(ls -la /opt/crypto-coach | head -5)"
          else
            echo "❌ /opt/crypto-coach directory NOT found"
          fi